# Generated by Django 3.0.5 on 2020-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.CharField(default='static/tile.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
