# Generated by Django 3.0.5 on 2020-05-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogedit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogedit',
        ),
    ]
