# Generated by Django 3.0.6 on 2020-06-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='blogpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Blogpost'),
            preserve_default=False,
        ),
    ]
