# Generated by Django 3.0.6 on 2020-06-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sources_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sources',
            new_name='Source',
        ),
    ]
