# Generated by Django 3.0.6 on 2020-06-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_source_decorator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='decorator',
        ),
    ]
