# Generated by Django 3.0.8 on 2020-07-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
