# Generated by Django 3.0.8 on 2020-07-24 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200724_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cover',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
